### Playbook to change root password
### To encrypt the password run this:
### python3 -c 'import crypt,getpass;pw=getpass.getpass();print(crypt.crypt(pw) if (pw==getpass.getpass("Confirm: ")) else exit())'
---
- hosts: all
  gather_facts: no
  become: yes
  
  tasks:
   - name: Update Root user's Password
     user: 
       name: root
       update_password: always 
       password: XXXXXXXXXXXXXXXXXX
